### ISSUE TITLE
Warn users about constructing values in `fmt_or_else`

### ISSUE THREAD

**Issue by Plecra** [TyPR124/fmtor#2]
https://github.com/TyPR124/fmtor/blob/594841925168cbfeafc32170a935c6cea98523fe/src/lib.rs#L204

`*_or_else` methods are typically used for lazy evaluation, where expensive work might be avoided. It may be surprising for users that the closure will be called every time the value is formatted, instead of once as `maybe_string.unwrap_or_else(|| String::from("Eheh"))` would.

It'd be fine to just add a note to the documentation explaining this behaviour, but it also highlights the issue that the fallback value must be `'static`. Maybe there's an alternative API that could be more flexible.

**Comment by TyPR124** [comment]
> It may be surprising for users that the closure will be called every time the value is formatted... It'd be fine to just add a note to the documentation explaining this behaviour

I can get behind adding this note to the docs.

> issue that the fallback value must be 'static

I'm not sure I understand this. Do you have an example that doesn't work? I believe this crate should work with any lifetime on `U` (provided you aren't breaking borrowing rules in some other way).

This works, for instance, though maybe I'm simplifying too much.

```rust
#[test]
fn test_non_static_u() {
    let opt: Option<Box<()>> = None;
    struct BorrowedStr<'a>(&'a str);
    impl Display for BorrowedStr<'_> {
        fn fmt(&self, out: &mut std::fmt::Formatter) -> std::fmt::Result {
            Display::fmt(self.0, out)
        }
    }
    let u_owned: String = "u".to_owned();
    let u_borrowed = BorrowedStr(&*u_owned);

    assert_eq!(
        "u",
        format!("{:p}", opt.fmt_or_else(||&u_borrowed))
    )
}
```

**Comment by TyPR124** [comment]
I've added a note to fmt_or_else, which you should see in the docs for 0.1.2 once they are generated. I'm closing this, but if you can come up with an example with a non-'static U, please open another issue as I'd like to address that if possible.
